<?php
          session_start();
          $jmeno = $_SESSION['username'];
          $pocetAktualne = json_decode($_POST['pocetAktualne']);
          $pocetCelkove = json_decode($_POST['pocetCelkove']);
          $hps = json_decode($_POST['hps']);
          $x1upKup = json_decode($_POST['x1upKup']);
          $x2upKup = json_decode($_POST['x2upKup']);
          $x3upKup = json_decode($_POST['x3upKup']);
          $x4upKup = json_decode($_POST['x4upKup']);
          $x5upKup = json_decode($_POST['x5upKup']);
          $x6upKup = json_decode($_POST['x6upKup']);
          $x7upKup = json_decode($_POST['x7upKup']);
          $x8upKup = json_decode($_POST['x8upKup']);
          $x9upKup = json_decode($_POST['x9upKup']);
          $x10upKup = json_decode($_POST['x10upKup']);
          $x11upKup = json_decode($_POST['x11upKup']);
          $x12upKup = json_decode($_POST['x12upKup']);
          $x13upKup = json_decode($_POST['x13upKup']);
          $x14upKup = json_decode($_POST['x14upKup']);
          $x15upKup = json_decode($_POST['x15upKup']);
          $x16upKup = json_decode($_POST['x16upKup']);
          $x17upKup = json_decode($_POST['x17upKup']);
          $pocetPrvnichUp = json_decode($_POST['pocetPrvnichUp']);
          $pocetDruhychUp = json_decode($_POST['pocetDruhychUp']);
          $pocetTretichUp = json_decode($_POST['pocetTretichUp']);
          $pocetCtvrtychUp = json_decode($_POST['pocetCtvrtychUp']);
          $pocetPatychUp = json_decode($_POST['pocetPatychUp']);
          $pocetSestychUp = json_decode($_POST['pocetSestychUp']);
          $pocetSedmychUp = json_decode($_POST['pocetSedmychUp']);

          $db = mysqli_connect("localhost", "root", "", "computerclicker");

          $neco = "SELECT idu FROM users WHERE name='$jmeno'";
          $result = $db->query($neco);
          $row = $result->fetch_assoc();
          $id =(int)$row["idu"];

          $sql = "UPDATE skore SET aktualne='$pocetAktualne' WHERE idu='$id'";
          $db->query($sql);
          $sql = "UPDATE skore SET celkove='$pocetCelkove' WHERE idu='$id'";
          $db->query($sql);
          $sql = "UPDATE skore SET hps='$hps' WHERE idu='$id'";
          $db->query($sql);

          $sql = "UPDATE pocetsup SET vlast='$x1upKup' WHERE idu='$id' AND idsup='1'";
          $db->query($sql);
          $sql = "UPDATE pocetsup SET vlast='$x2upKup' WHERE idu='$id' AND idsup='2'";
          $db->query($sql);
          $sql = "UPDATE pocetsup SET vlast='$x3upKup' WHERE idu='$id' AND idsup='3'";
          $db->query($sql);
          $sql = "UPDATE pocetsup SET vlast='$x4upKup' WHERE idu='$id' AND idsup='4'";
          $db->query($sql);
          $sql = "UPDATE pocetsup SET vlast='$x5upKup' WHERE idu='$id' AND idsup='5'";
          $db->query($sql);
          $sql = "UPDATE pocetsup SET vlast='$x6upKup' WHERE idu='$id' AND idsup='6'";
          $db->query($sql);
          $sql = "UPDATE pocetsup SET vlast='$x7upKup' WHERE idu='$id' AND idsup='7'";
          $db->query($sql);
          $sql = "UPDATE pocetsup SET vlast='$x8upKup' WHERE idu='$id' AND idsup='8'";
          $db->query($sql);
          $sql = "UPDATE pocetsup SET vlast='$x9upKup' WHERE idu='$id' AND idsup='9'";
          $db->query($sql);
          $sql = "UPDATE pocetsup SET vlast='$x10upKup' WHERE idu='$id' AND idsup='10'";
          $db->query($sql);
          $sql = "UPDATE pocetsup SET vlast='$x11upKup' WHERE idu='$id' AND idsup='11'";
          $db->query($sql);
          $sql = "UPDATE pocetsup SET vlast='$x12upKup' WHERE idu='$id' AND idsup='12'";
          $db->query($sql);
          $sql = "UPDATE pocetsup SET vlast='$x13upKup' WHERE idu='$id' AND idsup='13'";
          $db->query($sql);
          $sql = "UPDATE pocetsup SET vlast='$x14upKup' WHERE idu='$id' AND idsup='14'";
          $db->query($sql);
          $sql = "UPDATE pocetsup SET vlast='$x15upKup' WHERE idu='$id' AND idsup='15'";
          $db->query($sql);
          $sql = "UPDATE pocetsup SET vlast='$x16upKup' WHERE idu='$id' AND idsup='16'";
          $db->query($sql);
          $sql = "UPDATE pocetsup SET vlast='$x17upKup' WHERE idu='$id' AND idsup='17'";
          $db->query($sql);

          $sql = "UPDATE pocetup SET pocet='$pocetPrvnichUp' WHERE idu='$id' AND idup='1'";
          $db->query($sql);
          $sql = "UPDATE pocetup SET pocet='$pocetDruhychUp' WHERE idu='$id' AND idup='2'";
          $db->query($sql);
          $sql = "UPDATE pocetup SET pocet='$pocetTretichUp' WHERE idu='$id' AND idup='3'";
          $db->query($sql);
          $sql = "UPDATE pocetup SET pocet='$pocetCtvrtychUp' WHERE idu='$id' AND idup='4'";
          $db->query($sql);
          $sql = "UPDATE pocetup SET pocet='$pocetPatychUp' WHERE idu='$id' AND idup='5'";
          $db->query($sql);
          $sql = "UPDATE pocetup SET pocet='$pocetSestychUp' WHERE idu='$id' AND idup='6'";
          $db->query($sql);
          $sql = "UPDATE pocetup SET pocet='$pocetSedmychUp' WHERE idu='$id' AND idup='7'";
          $db->query($sql);
?>